CREATE DATABASE SoloMangia

CREATE TABLE UTENTI(
IDUTENTE int identity primary key,
NOME varchar(30),
COGNOME varchar(30),
PASS varchar(30),

)

CREATE TABLE CITTA(
IDCITTA INT IDENTITY PRIMARY KEY,
NOMECITTA VARCHAR(30),
ABBREVIAZIONECITTA VARCHAR(2)
)

CREATE TABLE RISTORANTI(
IDRISTORANTE int identity primary key,
IDCITTA INT FOREIGN KEY REFERENCES CITTA(IDCITTA),
NOMERISTORANTE varchar(30),
)

